version: "3.3"

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: Urlaubsgesellschaft
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp 
    ports:
      - "3000:3000"
